apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: raemylab-cert  #name of this object
  namespace: default #same namespace as 
spec:
  dnsNames:
    - raemylab.ch
  secretName: tls-secret
  issuerRef:
    name: acme-issuer-prod
    kind: ClusterIssuer