apiVersion: v1
kind: PersistentVolume
metadata:
  name: apache-pv-volume
  labels:
    type: local
spec:
  storageClassName: apache-pv
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/LedTable/www"