apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: apache
  name: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apache
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yaml
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.service: apache
    spec:
      containers:
        - image: ssl-https:latest
          imagePullPolicy: Never
          name: apache
          ports:
            - containerPort: 443
          resources: {}
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs
              name: apache-claim0
      restartPolicy: Always
      volumes:
        - name: apache-claim0
          persistentVolumeClaim:
            claimName: apache-claim0
status: {}
