apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-cert  #name of this object
  namespace: default #same namespace as 
spec:
  dnsNames:
    - raemylab.ch
  secretName: tls-cert
  issuerRef:
    name: acme-issuer
    kind: ClusterIssuer