apiVersion: v1
kind: PersistentVolume
metadata:
  name: nginx-pv-config
  labels:
    type: local
spec:
  storageClassName: nginx-pv-config
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/LedTable/docker/conf"