apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx-svc
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    name: "http"
    protocol: TCP
    targetPort: 80
  spec:
  type: ClusterIP