apiVersion: v1
kind: PersistentVolume
metadata:
  name: table-api-pv-volume
  labels:
    type: local
spec:
  storageClassName: table-api-pv
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/ubuntu/LedTable/api/app"
